name: test-branch-x
on:
  push:
    branches:
      - X
jobs:
  test-x:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Test
        run: echo "Hello"
