name: update-branch
on:
  push:
    branches:
      - X
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Test
        run: echo "Hello"
